version: '3.8'

services:
  database:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: file_upload
    ports:
      - "15432:5432"
  php-fpm:
    container_name: php-fpm
    build:
      context: .deployments/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/var/www
  nginx:
    container_name: nginx
    build:
      context: .deployments/nginx
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/
      - ./nginx/sites:/etc/nginx/sites-available/
      - ./nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"